name: "Grafana Build Plugin"
description: "Builds a Grafana plugin"

# inputs:

runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v3
      with:
        node-version: 20
    - name: Install dependencies
      run: ${{ github.action_path }}/pm.sh install
      shell: bash
