name: "Grafana Build Plugin"
description: "Builds a Grafana plugin"

# inputs:

runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v3
      with:
        node-version: 20
    - run: ${{ github.action_path }}/build-packages.sh
      shell: bash
